import { cx } from '#/styled-system/css';
import type { Metadata } from 'next';
import { Andika, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const andika = Andika({
  variable: '--font-ndika',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cx(andika.variable, geistSans.variable, geistMono.variable)}>
        {children}
      </body>
    </html>
  );
}
